name: mad1
description: A mobile banking application prototype.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  cloud_firestore: null
  firebase_auth: null
  firebase_core: null
  firebase_database: null
  flutter:
    sdk: flutter
  flutter_lints: null
  google_fonts: null
  graphql_flutter: null
  http: null
  provider: null
  stroke_text: ^1.0.0
  local_auth:
  intl: ^0.17.0
  flutter_riverpod: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.jpg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
